before_script:
  - npm install

stages:
  - build
  - test
  - deploy

build:
  image: node:18.15
  stage: build 
  script: 
    - npm install


test:
  image: node:18.15
  stage: test
  script:
    - npm test

heroku:
  image: node:18.15
  stage: deploy
  only:
    - main

  script:
    - apt-get update -qy
    - apt-get install -y ruby
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY