before_script:
  - npm install

stages:
  - build
  - test
  - deploy

build:
  image: node:12-alpine
  stage: build 
  script: 
    - npm install


test:
  image: node:12-alpine
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - echo "Desplegando el proyecto en producción"
