stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Construyendo el proyecto"

test:
  stage: test
  script:
    - echo "Ejecutando pruebas automatizadas"

deploy:
  stage: deploy
  script:
    - echo "Desplegando el proyecto en producción"
