before_script:
  - npm install

stages:
  - build
  - test
  - deploy

build:
  image: node:18.15
  stage: build 
  script: 
    - npm install


test:
  image: node:18.15
  stage: test
  script:
    - npm test

deploy:
  image: node:18.15
  stage: deploy
  script:
    - echo "Desplegando el proyecto en producción"
